# Generated by Django 3.2.3 on 2021-11-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=2000)),
                ('punctuation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mail', models.CharField(default='', max_length=30)),
                ('nickname', models.CharField(default='NULL', max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('t1_punct', models.IntegerField(default=0)),
                ('t2_punct', models.IntegerField(default=0)),
                ('done_test', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1440)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
