# Generated by Django 3.2.3 on 2021-11-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('done_test', models.BooleanField(default=False)),
            ],
        ),
    ]
