# Generated by Django 3.2.3 on 2021-11-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('t1_punct', models.IntegerField(default=0)),
                ('t2_punct', models.IntegerField(default=0)),
                ('ts_punct1', models.IntegerField(default=0)),
                ('ts_punct2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Cuestionario',
            fields=[
                ('id_pregunta', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('id_cuestionario', models.IntegerField(default=0)),
                ('invertida', models.IntegerField(default=0)),
                ('respuesta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1440)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
