# Generated by Django 3.2.9 on 2021-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta_Cuestionario',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cuestionario', models.IntegerField(default=0)),
                ('invertida', models.IntegerField(default=0)),
                ('respuesta', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
