# Generated by Django 3.2.3 on 2021-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_test',
            field=models.BooleanField(default=False),
        ),
    ]
