# Generated by Django 3.2.3 on 2021-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_done_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=2000)),
                ('punctuation', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='t1_punct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='t2_punct',
            field=models.IntegerField(default=0),
        ),
    ]
