# Generated by Django 3.2.3 on 2021-12-10 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 16, 3, 0, 337044, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
